version: '3.8'

services:
  # Servicio de producción local (web)
  web_site_prod:
    build:
      context: .
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=prod
      - PG_PROD_HOST=${PG_PROD_HOST}
      - PG_PROD_DATABASE=${PG_PROD_DATABASE}
      - PG_PROD_USER=${PG_PROD_USER}
      - PG_PROD_PASSWORD=${PG_PROD_PASSWORD}
      - PG_PROD_PORT=${PG_PROD_PORT}
      - PG_PROD_SSL=${PG_PROD_SSL}
      - ZOHO_PROD_CLIENT_ID=${ZOHO_PROD_CLIENT_ID}
      - ZOHO_PROD_CLIENT_SECRET=${ZOHO_PROD_CLIENT_SECRET}
      - ZOHO_PROD_REFRESH_TOKEN=${ZOHO_PROD_REFRESH_TOKEN}
      - PORT=6000
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
  
  postgres:
    image: postgres:13
    container_name: dev_postgres_data
    environment:
      - POSTGRES_USER=${PG_PROD_USER}
      - POSTGRES_PASSWORD=${PG_PROD_PASSWORD}
      - POSTGRES_DB=${PG_PROD_DATABASE}
    volumes:      
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_PROD_USER} -d ${PG_PROD_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: